print("MU/TH/UR")
print(" ")
print("INTERFACE 2037 READY FOR INQUIRY")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("REQUEST CLARIFICATION ON")
print("SCIENCE INABILITY TO NEUTRALIZE ALIEN")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("UNABLE TO CLARIFY")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print(" ")
print("REQUEST ENHANCEMENT")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("NO FURTHER ENHANCEMENT")
print("SPECIAL ORDER 937")
print("SCIENCE OFFICER EYES ONLY")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print(" ")
print("EMERGENCY COMMAND OVERRIDE 100375")
print("WHAT IS SPECIAL ORDER 937 ?")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print(" ")
print("NOSTROMO REROUTED")
print("TO NEW CO-ORDINATES.")
print("INVESTIGATE LIFE FORM. GATHER SPECIMEN.")
print(" ")
print("PRIORITY ONE")
print("INSURE RETURN OF ORGANISM")
print("FOR ANALYSIS.")
print("ALL OTHER CONSIDERATIONS SECONDARY.")
print("CREW EXPENDABLE.")
print(" ")
print(" ")
print(" ")
print("IT LOOKS LIKE YOU'RE INSURING THE RETURN OF ORGANISM FOR ANALYSIS.")
print(" ")
print("WOULD YOU LIKE HELP?")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("* GET HELP INSURING RETURN OF ORGANISM FOR ANALYSIS")
print(" ")
print("* JUST RETURN THE ORGANISM FOR ANALYSIS WITHOUT HELP")
print(" ")
print("[ ] DON'T SHOW ME THIS TIP AGAIN")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("[X] DON'T SHOW ME THIS TIP AGAIN")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("THANK YOU FOR CHOOSING WEYLAND-YUTANI FOR ALL YOUR ORGANISM RETURNING NEEDS")
print(" ")